title                   : "The Brooklyn Rail"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "brooklynrail"
themesDir               : "./themes"
MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 20
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true
enableGitInfo           : true
buildFuture             : true
relativeURLs            : true


# HUGO will ignore pages in the following folders
ignoreFiles:
  - "^_template"
  - "content/_archived/*"

permalinks:
  article               : ":year/:month/:day/:slug/"
  events                : "events/:year/:month/:day/:slug/"


.params:
  events_count: 20
  articles_count: 20

menu:
  primary:
    
    - Name            : "&#8810; Current Issue"
      Identifier      : "home"
      URL             : "/"
      Weight          : 1
    - Name            : "Events"
      Identifier      : "events"
      URL             : "/events/"
      Weight          : 2
    - Name            : "Store"
      Identifier      : "store"
      URL             : "https://shop.brooklynrail.org/"
      Weight          : 3
    - Name            : "Newsletter"
      Identifier      : "newsletter"
      URL             : "/newsletter/"
      Weight          : 4
    - Name            : "About"
      Identifier      : "about"
      URL             : "/about/"
      Weight          : 4
