[build]
publish = "public"
functions = "netlify_functions"
command = "gulp build && netlify-lambda && netlify_functions && hugo --gc --minify -b $URL"

[context.production.environment]
HUGO_VERSION = "0.69.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.69.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "gulp build && hugo --gc --minify --buildFuture -b $DEPLOY_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.0"

[context.branch-deploy]
command = "gulp build && hugo --gc --minify -b $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://brooklynrail.org"
