# The Brooklyn Rail / Editing Workflow
# https://brooklynrail.org/workflow

# ====================================

display_url: https://brooklynrail.org
site_url: https://brooklynrail.org

# logo_url — sets the logo in the admin
logo_url: https://brooklynrail.org/images/dist/brooklynrail-logo-red.png

# Backend and connections
backend:
  name: github
  repo: brooklynrail/brooklynrail-platform
  site_domain: brooklynrail.netlify.com
  base_url: https://api.netlify.com
  open_authoring: true # accept contributions (forks) from GitHub users
  branch: master
  squash_merges: true # squash all commits into a single commit when the PR is merged
  commit_messages:
    create: 'New {{collection}}: "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: '{{message}}, {{author-login}}'

# Enables the NetlifyCMS editorial workflow tools
publish_mode: editorial_workflow

# Media / Images
# This is where media will be stored in the repo
media_folder: "static/media"
# Path for uploaded media on the live site
public_folder: "/media"

# slug — sets how filenames for entries are created and sanitized.
slug:
  encoding: "unicode"
  clean_accents: true

# Localhost Editing
# uses the local proxy server port set in the `npx netlify-cms-proxy-server` command
# (see the workflow script in packages.json)
local_backend:
  url: http://localhost:8081/api/v1



# ==============================================
# Content Collections
collections:


  # EVENTS Collection =======================
  - name: "events-beta" # Used in routes, e.g., /workflow/collections/blog
    label: "Events" # Used in the UI
    label_singular: "Event"
    description: "TKTK"
    folder: "content/events-beta" # path to the folder where files are stored
    path: '{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}' # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.

    fields: # The fields for each document, usually in frontmatter

      - label: "Kicker"
        name: "kicker"
        widget: "string"
        default: "The New Social Environment"
        hint: "TKTK"
        required: false

      - label: "Event Title"
        name: "title"
        minimal: true
        widget: "string"
        hint: "TKTK"

      - label: "Deck"
        name: "deck"
        minimal: true
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Summary"
        name: "summary"
        minimal: true
        widget: "string"
        default: "Artist **NAME_NAME** with writer **NAME_NAME**, discuss creative life in the context of our new social reality."
        hint: "TKTK"

      - label: "Event Host"
        name: "event_host"
        widget: "string"
        hint: "TKTK"
        default: "The Brooklyn Rail"
        required: false

      - label: "Event Organizer"
        name: "event_organizer"
        widget: "string"
        hint: "TKTK"
        default: "The Brooklyn Rail"
        required: false

      - label: "Event Sponsor"
        name: "event_sponsor"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Registration URL"
        name: "registration_url"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "YouTube ID"
        name: "youtube_id"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "YouTube Playlist ID"
        name: "youtube_playlist_id"
        widget: "string"
        default: "PLmQDwVpMadcLGDOX9VN3sGTh2VYT4RJGY"
        hint: "TKTK"
        required: false

      - label: "Start time"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 -0500"

      - label: "End time"
        name: "end_date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 24.12.2021
        timeFormat: "HH:00" # e.g. 21:07
        default: true
        format: "YYYY-MM-DD HH:mm:00 -0500"
        required: false

      - label: "Event Platform"
        name: "event_platform"
        widget: "select"
        multiple: true
        options: ["zoom", "youtube", "instagram_live", "igtv"]
        hint: "TKTK"
        default: ["zoom"]
        required: false

      - label: "Featured Images"
        name: "featured_images"
        widget: 'list'
        hint: "Upload images through the OLD RAIL admin"
        required: false
        fields:
          - { label: 'Image URL', name: 'img_url', widget: 'string' }

      - label: "Event Copy"
        name: "body"
        widget: 'markdown'
        required: false





  # AUTHORS Collection =======================
  - name: "authors" # Used in routes, e.g., /workflow/collections/blog
    label: "Authors" # Used in the UI
    label_singular: 'Author'
    description: "TKTK"
    folder: "content/authors" # path to the folder where files are stored
    path: '{{slug}}/_index' # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: display_name # sets the field that is used to create the slug
    slug: "{{slug}}"

    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.

    fields: # The fields for each document, usually in frontmatter

      - label: "Display Name"
        name: "display_name"
        widget: "string"
        hint: "TKTK"

      - label: "First Name"
        name: "first_name"
        widget: "string"
        hint: "TKTK"

      - label: "Last Name"
        name: "last_name"
        widget: "string"
        hint: "TKTK"

      - label: "Pronoun"
        name: "pronoun"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Email"
        name: "email"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Bio"
        name: "bio"
        widget: "text"
        hint: "TKTK"
        required: false

      - label: "Bio URL"
        name: "bio_url"
        widget: "text"
        hint: "Provide a full URL to where people can learn more about your work."
        required: false

      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "Enter your username without the @ handle [e.g. brooklynrail]"
        required: false

      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false

      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false

      - label: "Linkedin"
        name: "linkedIn"
        widget: "string"
        required: false

      - label: "YouTube"
        name: "youtube"
        widget: "string"
        required: false


  # MEDIA Collection =======================
  - name: "media" # Used in routes, e.g., /workflow/collections/blog
    label: "Media" # Used in the UI
    label_singular: 'Media'
    description: "TKTK"
    folder: "content/media" # path to the folder where files are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name # sets the field that is used to create the slug
    slug: "{{year}}/{{month}}/{{slug}}"

    fields: # The fields for each document, usually in frontmatter

      - label: "Media"
        name: "media"
        widget: "image"
        hint: "TKTK"
        prompt: true
        media_library:
          config:
            multiple: true
        fields:
          - label: "Names"
            name: "names"
            widget: "string"
            hint: "TKTK"


      - label: "Name"
        name: "name"
        widget: "string"
        hint: "TKTK"

      - label: "Image Alt"
        name: "alt"
        widget: "string"
        hint: "TKTK"

      - label: "Image Caption"
        name: "caption"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Image Credit"
        name: "credit"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 -0500"
