# The Brooklyn Rail / Editing Workflow
# https://brooklynrail.org/workflow

# ====================================

display_url: https://brooklynrail.org
site_url: https://brooklynrail.org

# logo_url — sets the logo in the admin
logo_url: https://brooklynrail.org/images/dist/brooklynrail-logo-red.png

# Backend and connections
backend:
  name: git-gateway
  repo: brooklynrail/brooklynrail-platform
  site_domain: brooklynrail.netlify.com
  base_url: https://api.netlify.com
  open_authoring: false # accept contributions (forks) from GitHub users
  branch: master
  squash_merges: true # squash all commits into a single commit when the PR is merged
  commit_messages:
    create: 'New {{collection}}: "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: "{{message}}, {{author-login}}"

# Enables the NetlifyCMS editorial workflow tools
# publish_mode: editorial_workflow

# Media / Images
# This is where media will be stored in the repo
media_folder: "/static/media/{{year}}/{{month}}/"
# Path for uploaded media on the live site
public_folder: "/media"

# slug — sets how filenames for entries are created and sanitized.
slug:
  encoding: "unicode"
  clean_accents: true

# Localhost Editing
# uses the local proxy server port set in the `npx netlify-cms-proxy-server` command
# (see the workflow script in packages.json)
local_backend:
  url: http://localhost:8081/api/v1

# ==============================================
# Content Collections
collections:
  # EVENTS Collection =======================
  - name: "events-beta" # Used in routes, e.g., /workflow/collections/blog
    label: "Events" # Used in the UI
    label_singular: "Event"
    description: "TKTK"
    folder: "content/events-beta" # path to the folder where files are stored
    media_folder: "/static/media/{{year}}/{{month}}/"
    path: "{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.

    fields: # The fields for each document, usually in frontmatter
      - label: "Event Title"
        name: "title"
        minimal: true
        widget: "string"
        hint: "Keep it short and topical, no acronyms."

      - label: "Deck"
        name: "deck"
        minimal: true
        widget: "string"
        hint: "A continuation of the headline, without repeating it. Think of this as the sentence you'd most like to tweet. You need to be able to read it outloud in a single breath."
        required: false

      - label: "Summary"
        name: "summary"
        minimal: true
        widget: "string"
        default: ""
        hint: "One-sentence description of the event. _(e.g. Artist [Name] with writer [Name], discuss creative life in the context of our new social reality.)_"

      - label: "Event Copy"
        name: "body"
        widget: "markdown"
        editorComponents: ["image"]
        required: false

      - label: "Start time"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        default: "2020-05-20 13:00"
        hint: "The start date and time of the event (Note: uses a 24hr clock, e.g. 13:00)"

      - label: "End time"
        name: "end_date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        default: "2020-05-20 14:00"
        hint: "The end date and time of the event (Note: uses a 24hr clock, e.g. 14:00)"

      - label: "Collections"
        name: "collections"
        widget: "relation"
        multiple: true
        collection: "collections"
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["{{title}}"]
        default: ["the-new-social-environment"]
        hint: "Select the collections this event should be included in."
        required: false

      - label: "Event Sponsor"
        name: "event_sponsor"
        widget: "string"
        hint: "The name of the sponsor, no links."
        required: false

      - label: "Event Host"
        name: "event_host"
        widget: "string"
        hint: "The organizization that is responsible for the content of the talk (usually The Brooklyn Rail)"
        default: "The Brooklyn Rail"
        required: false

      - label: "Event Organizer"
        name: "event_organizer"
        widget: "string"
        hint: "The organizization that is responsible for the production of the talk (usually The Brooklyn Rail)."
        default: "The Brooklyn Rail"
        required: false

      - label: "Registration URL"
        name: "registration_url"
        widget: "string"
        hint: "A link to Eventbrite, or where our readers are being asked to register. (e.g. https://www.eventbrite.com/...)"
        required: false

      - label: "YouTube ID"
        name: "youtube_id"
        widget: "string"
        hint: "The YouTube ID is the string of characters between the `v=` and the `&` in the video URL. (e.g. `3FKyVeipMss`)"
        required: false

      - label: "YouTube Playlist ID"
        name: "youtube_playlist_id"
        widget: "select"
        multiple: true
        options: ["the-new-social-environment"]
        hint: "Select the YouTube playlist where you can find this video"
        default: ["the-new-social-environment"]
        required: false

      - label: "Event Platform"
        name: "event_platform"
        widget: "select"
        multiple: true
        options: ["zoom", "youtube", "instagram_live", "igtv"]
        hint: "TKTK"
        default: ["zoom"]
        required: false

      - label: "Featured Images"
        name: "featured_images"
        widget: "list"
        hint: "These are the images that will show up in social media."
        required: false
        fields:
          - label: "Media"
            name: "media"
            widget: "relation"
            collection: "media"
            searchFields: ["media", "title"]
            valueField: "{{slug}}"
            required: false
            displayFields: ["{{title}} — {{date}}"]


  # AUTHORS Collection =======================
  - name: "authors" # Used in routes, e.g., /workflow/collections/blog
    label: "Authors" # Used in the UI
    label_singular: "Author"
    description: "TKTK"
    folder: "content/authors" # path to the folder where files are stored
    path: "{{slug}}/_index" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: display_name # sets the field that is used to create the slug
    slug: "{{slug}}"

    # Field Settings
    # - label     — the title that will appear above the field in the editor
    # - name      — this is the key that will be used in the front matter
    # - widget    — the type of field — See https://www.netlifycms.org/docs/widgets/ for all types
    # - required  — all fields are required by default unless you include `required: false`
    # - hint  — this is the helper text that occurrs below the field.

    fields: # The fields for each document, usually in frontmatter
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        hint: "TKTK"

      - label: "First Name"
        name: "first_name"
        widget: "string"
        hint: "TKTK"

      - label: "Last Name"
        name: "last_name"
        widget: "string"
        hint: "TKTK"

      - label: "Pronoun"
        name: "pronoun"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Email"
        name: "email"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Bio"
        name: "bio"
        widget: "text"
        hint: "TKTK"
        required: false

      - label: "Bio URL"
        name: "bio_url"
        widget: "text"
        hint: "Provide a full URL to where people can learn more about your work."
        required: false

      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "Enter your username without the @ handle [e.g. brooklynrail]"
        required: false

      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false

      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false

      - label: "Linkedin"
        name: "linkedIn"
        widget: "string"
        required: false

      - label: "YouTube"
        name: "youtube"
        widget: "string"
        required: false

  # MEDIA Collection =======================
  - name: "media" # Used in routes, e.g., /workflow/collections/blog
    label: "Media" # Used in the UI
    label_singular: "Media"
    description: "TKTK"
    folder: "data/media/" # path to the folder where files are stored
    media_folder: "/static/media/{{year}}/{{month}}/"
    public_folder: "/media"
    path: "{{year}}/{{month}}/{{slug}}"
    extension: "yml"
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{title}}"
    summary: "{{title}} ({{year}}-{{month}})"

    fields: # The fields for each document, usually in frontmatter
      - label: "Media"
        name: "media"
        widget: "image"
        filename: "{{title}}"
        hint: "TKTK"
        prompt: true
        media_library:
          config:
            multiple: true

      - label: "Image title"
        name: "title"
        widget: "string"
        hint: "TKTK"

      - label: "Image Alt"
        name: "alt"
        widget: "string"
        hint: "TKTK"

      - label: "Image Caption"
        name: "caption"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Image Credit"
        name: "credit"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 -0500"



  # Collections Collection =======================
  # NOTE: the word "collection" is being used in the RAIL site as a replacement for section. It is also a word to describe a grouping of content in Netlify CMS.

  - name: "collections" # Used in routes, e.g., /workflow/collections/blog
    label: "Collections" # Used in the UI
    label_singular: "Collection"
    description: "A group of similar content."
    folder: "content/collections" # path to the folder where files are stored
    path: "{{slug}}/_index" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    fields: # The fields for each document, usually in frontmatter
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "TKTK"

      - label: "Deck"
        name: "deck"
        widget: "string"
        hint: "TKTK"

      - label: "Summary"
        name: "summary"
        widget: "string"
        hint: "TKTK"

      - label: "YouTube Playlist ID"
        name: "youtube_playlist_id"
        widget: "string"
        hint: "TKTK"
