# The Brooklyn Rail / Editing Workflow
# https://brooklynrail.org/workflow


# ====================================
display_url: https://brooklynrail.org
site_url: https://brooklynrail.org

# logo_url — sets the logo in the admin
logo_url: https://brooklynrail.org/images/dist/brooklynrail-logo-red.png


# ====================================
# Account settings
backend:
  name: git-gateway
  repo: brooklynrail/brooklynrail-platform
  site_domain: brooklynrail.netlify.com
  base_url: https://api.netlify.com


  # ====================================
  # Workflow -- NetlifyCMS editorial workflow tools
  # publish_mode: editorial_workflow
  open_authoring: false # accept contributions (forks) from GitHub users
  branch: master
  squash_merges: true # squash all commits into a single commit when the PR is merged
  commit_messages:
    create: 'New {{collection}}: "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'
    openAuthoring: "{{message}}, {{author-login}}"


# ====================================
# Media
# Where media will be stored in the repo
media_folder: "/static/media/files"
# Path for uploaded media on the live site
public_folder: "/media/files"


# ====================================
# Configuration
# slug — sets how filenames for entries are created and sanitized.
slug:
  encoding: "unicode"
  clean_accents: true


# Localhost Editing
# uses the local proxy server port set in the `npx netlify-cms-proxy-server` command
# (see the workflow script in packages.json)
local_backend:
  url: http://localhost:8081/api/v1

# ====================================
# Collections
collections:


  # ====================================
  # Events
  - name: "events-beta" # Used in routes, e.g., /workflow/collections/blog
    label: "Events" # Used in the UI
    label_singular: "Event"
    description: "TKTK"
    folder: "content/events-beta" # path to the folder where files are stored
    path: "{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"
    summary: "{{title}} ({{year}}-{{month}}-{{day}})"
    editor:
      preview: false

    fields: # The fields for each document, usually in frontmatter
      - label: "Event Title"
        name: "title"
        minimal: true
        widget: "string"
        hint: "Keep it short and topical, no acronyms."

      - label: "Deck"
        name: "deck"
        minimal: true
        widget: "string"
        hint: "A continuation of the headline, without repeating it. Think of this as the sentence you'd most like to tweet. You need to be able to read it outloud in a single breath."
        required: false

      - label: "Summary"
        name: "summary"
        minimal: true
        widget: "string"
        default: ""
        hint: "One-sentence description of the event. _(e.g. Artist [Name] with writer [Name], discuss creative life in the context of our new social reality.)_"

      - label: "Event Copy"
        name: "body"
        widget: "markdown"
        editorComponents: ["image"]
        required: false

      - label: "Start time"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        default: "2020-05-20 13:00"
        hint: "The start date and time of the event (Note: uses a 24hr clock, e.g. 13:00)"

      - label: "End time"
        name: "end_date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 2021-11.23
        timeFormat: "HH:mm" # e.g. 21:00
        format: "YYYY-MM-DD HH:mm:00 -0500"
        default: "2020-05-20 14:00"
        hint: "The end date and time of the event (Note: uses a 24hr clock, e.g. 14:00)"

      - label: "Series number"
        name: "series"
        widget: "number"
        valueType: "int"
        min: 1
        required: false

      - label: "Collections"
        name: "collections"
        widget: "relation"
        multiple: true
        collection: "collections"
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["{{title}}"]
        default: ["the-new-social-environment"]
        hint: "Select the collections this event should be included in."
        required: false

      - label: "Event Sponsor"
        name: "event_sponsor"
        widget: "relation"
        multiple: true
        collection: "organizations"
        searchFields: ["name", "short_desc"]
        valueField: "{{slug}}"
        displayFields: ["{{name}}"]
        default: ["the-brooklyn-rail"]
        hint: "Select the organizations that are sponsoring this event."
        required: false

      - label: "Event Organizer"
        name: "event_organizer"
        widget: "relation"
        multiple: true
        collection: "organizations"
        searchFields: ["name", "short_desc"]
        valueField: "{{slug}}"
        displayFields: ["{{name}}"]
        default: ["the-brooklyn-rail"]
        hint: "Select the organizations that should be credited pulling togther the content of the talk."
        required: false

      - label: "Event Producer"
        name: "event_producer"
        widget: "relation"
        multiple: true
        collection: "organizations"
        searchFields: ["name", "short_desc"]
        valueField: "{{slug}}"
        displayFields: ["{{name}}"]
        default: ["the-brooklyn-rail"]
        hint: "Select the organization that should be credited with producing the event."

      - label: "Registration URL"
        name: "registration_url"
        widget: "string"
        hint: "A link to Eventbrite, or where our readers are being asked to register. (e.g. https://www.eventbrite.com/...)"
        required: false

      - label: "YouTube ID"
        name: "youtube_id"
        widget: "string"
        hint: "The YouTube ID is the string of characters between the `v=` and the `&` in the video URL. (e.g. `3FKyVeipMss`)"
        required: false

      - label: "Event Platform"
        name: "event_platform"
        widget: "select"
        multiple: true
        options: ["zoom", "youtube", "instagram_live", "igtv"]
        hint: "Zoom, youtube, instagram_live, igtv"
        default: ["zoom"]
        required: false

      - label: "Featured Images"
        name: "featured_images"
        widget: "list"
        hint: "These are the images that will show up in social media."
        required: false
        fields:
          - label: "Media"
            name: "media"
            widget: "relation"
            collection: "media"
            searchFields: ["media", "title"]
            valueField: "{{slug}}"
            required: false
            displayFields: ["{{title}} — {{date}}"]



  # ====================================
  # Media

  - name: "media" # Used in routes, e.g., /workflow/collections/blog
    label: "Media" # Used in the UI
    label_singular: "Media"
    description: "TKTK"
    folder: "content/media/" # path to the folder where files are stored
    media_folder: "/static/media/files/"
    public_folder: "/media/files/"
    path: "/{{year}}/{{month}}/{{slug}}"
    extension: "md"
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{title}}"
    summary: "{{title}} ({{year}}-{{month}})"
    editor:
      preview: false

    fields: # The fields for each document, usually in frontmatter
      - label: "Media"
        name: "media"
        widget: "image"
        hint: "TKTK"
        prompt: true
        media_library:
          config:
            multiple: true

      - label: "Image title"
        name: "title"
        widget: "string"
        hint: "TKTK"

      - label: "Image Alt"
        name: "alt"
        widget: "string"
        hint: "TKTK"

      - label: "Image Caption"
        name: "caption"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Image Credit"
        name: "credit"
        widget: "relation"
        multiple: true
        collection: "people"
        searchFields: ["name"]
        valueField: "{{slug}}"
        displayFields: ["{{name}}"]
        hint: "This is the person who will receive credit as the author of the image."
        required: false


      - label: "Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD" # e.g. 24.12.2021
        timeFormat: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 -0500"


  # ====================================
  # Collections
  # NOTE: the word "collection" is being used in the RAIL site as a replacement for section. It is also a word to describe a grouping of content in Netlify CMS. In this case, the specific name of the collection is 'collections'.

  - name: "collections" # Used in routes, e.g., /workflow/collections/blog
    label: "Collections" # Used in the UI
    label_singular: "Collection"
    description: "A group of similar content."
    folder: "content/collections" # path to the folder where files are stored
    path: "{{slug}}" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: title # sets the field that is used to create the slug
    slug: "{{slug}}"

    fields: # The fields for each document, usually in frontmatter
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "TKTK"

      - label: "Deck"
        name: "deck"
        widget: "string"
        hint: "TKTK"

      - label: "Summary"
        name: "summary"
        widget: "string"
        hint: "TKTK"

      - label: "YouTube Playlist ID"
        name: "youtube_playlist_id"
        widget: "string"
        hint: "TKTK"


  # ====================================
  # People

  - name: "people" # Used in routes, e.g., /workflow/collections/blog
    label: "People" # Used in the UI
    label_singular: "Person"
    description: "People in the Rail community"
    folder: "content/people" # path to the folder where files are stored
    path: "{{slug}}" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: name # sets the field that is used to create the slug
    slug: "{{slug}}"

    fields: # The fields for each document, usually in frontmatter
      - label: "Display Name"
        name: "name"
        widget: "string"
        hint: "TKTK"

      - label: "First Name"
        name: "first_name"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Last Name"
        name: "last_name"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Pronouns"
        name: "pronouns"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Short Bio"
        name: "short_bio"
        widget: "text"
        pattern: ['^.{0,240}$', "Short bio needs to be less than240 characters"]
        hint: "Add a short description of the person without using their name. [Max 240 characters]"
        required: false

      - label: "Email"
        name: "email"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Website"
        name: "website"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Instagram"
        name: "instagram"
        widget: "string"
        required: false

      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "Enter your username without the @ handle [e.g. brooklynrail]"
        required: false

      - label: "Linkedin"
        name: "linkedIn"
        widget: "string"
        required: false



  # ====================================
  # Organizations

  - name: "organizations" # Used in routes, e.g., /workflow/collections/blog
    label: "Organizations" # Used in the UI
    label_singular: "Organization"
    description: "Organizations in the Rail community"
    folder: "content/organizations" # path to the folder where files are stored
    path: "{{slug}}" # custom file path
    create: true # Allow users to create new documents in this collection
    identifier_field: name # sets the field that is used to create the slug
    slug: "{{slug}}"

    fields: # The fields for each document, usually in frontmatter
      - label: "Organization Name"
        name: "name"
        widget: "string"
        hint: "TKTK"

      - label: "Short description"
        name: "short_desc"
        widget: "text"
        hint: "TKTK"
        required: false

      - label: "Primary Email"
        name: "email"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Website"
        name: "website"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Instagram"
        name: "instagram"
        widget: "string"
        hint: "TKTK"
        required: false

      - label: "Twitter"
        name: "twitter"
        widget: "string"
        hint: "TKTK"
        required: false
